dist: xenial
language: php
php:
  - 7.3
cache:
  files:
    - ./.php_cs.cache
  directories:
    - ./vendor/
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
script:
  - composer run tests
matrix:
  fast_finish: true
